Add portaudio_a.c

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -310,7 +310,7 @@ ac_includes_default="\
 # include <unistd.h>
 #endif"
 
-ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM AWK SET_MAKE am__leading_dot MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT EMACS lispdir CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CPP EGREP RANLIB ac_ct_RANLIB LN_S X_CFLAGS X_PRE_LIBS X_LIBS X_EXTRA_LIBS LIBOBJS ALSA_CFLAGS ALSA_LIBS ARTS_CONFIG ARTS_CFLAGS ARTS_LIBS ESD_CONFIG ESD_CFLAGS ESD_LIBS VORBIS_CFLAGS VORBIS_LIBS VORBISFILE_LIBS VORBISENC_LIBS OGG_CFLAGS OGG_LIBS NEEDDLOPEN_TRUE NEEDDLOPEN_FALSE ENABLE_NCURSES_TRUE ENABLE_NCURSES_FALSE n_so_libs ENABLE_SLANG_TRUE ENABLE_SLANG_FALSE s_so_libs ENABLE_MOTIF_TRUE ENABLE_MOTIF_FALSE m_so_libs ENABLE_TCLTK_TRUE ENABLE_TCLTK_FALSE k_so_libs ENABLE_DYNAMIC_TCLTK_TRUE ENABLE_DYNAMIC_TCLTK_FALSE ENABLE_EMACS_TRUE ENABLE_EMACS_FALSE e_so_libs ENABLE_VT100_TRUE ENABLE_VT100_FALSE T_so_libs ENABLE_XAW_TRUE ENABLE_XAW_FALSE a_so_libs ENABLE_DYNAMIC_XAW_TRUE ENABLE_DYNAMIC_XAW_FALSE ENABLE_XSKIN_TRUE ENABLE_XSKIN_FALSE i_so_libs ENABLE_GTK_TRUE ENABLE_GTK_FALSE GTK_CONFIG GTK_CFLAGS GTK_LIBS g_so_libs ENABLE_SERVER_TRUE ENABLE_SERVER_FALSE r_so_libs ENABLE_ALSASEQ_TRUE ENABLE_ALSASEQ_FALSE A_so_libs ENABLE_WINSYN_TRUE ENABLE_WINSYN_FALSE W_so_libs ENABLE_W32GUI_TRUE ENABLE_W32GUI_FALSE w_so_libs ENABLE_PLUGIN_TRUE ENABLE_PLUGIN_FALSE p_so_libs ENABLE_NETWORK_TRUE ENABLE_NETWORK_FALSE ENABLE_SOUND_SPEC_TRUE ENABLE_SOUND_SPEC_FALSE ENABLE_WRD_TRUE ENABLE_WRD_FALSE CYGNUS_TRUE CYGNUS_FALSE MINGW_TRUE MINGW_FALSE W32READDIR_TRUE W32READDIR_FALSE timidity_LDFLAGS SYSEXTRAS EXTRALIBS NETSRCS ELFILES SHLD SHCFLAGS dynamic_targets so WISH tcltk_dep INTERFACE_SRCS pkgdatadir pkglibdir LTLIBOBJS'
+ac_subst_vars='SHELL PATH_SEPARATOR PACKAGE_NAME PACKAGE_TARNAME PACKAGE_VERSION PACKAGE_STRING PACKAGE_BUGREPORT exec_prefix prefix program_transform_name bindir sbindir libexecdir datadir sysconfdir sharedstatedir localstatedir libdir includedir oldincludedir infodir mandir build_alias host_alias target_alias DEFS ECHO_C ECHO_N ECHO_T LIBS build build_cpu build_vendor build_os host host_cpu host_vendor host_os target target_cpu target_vendor target_os INSTALL_PROGRAM INSTALL_SCRIPT INSTALL_DATA CYGPATH_W PACKAGE VERSION ACLOCAL AUTOCONF AUTOMAKE AUTOHEADER MAKEINFO AMTAR install_sh STRIP ac_ct_STRIP INSTALL_STRIP_PROGRAM AWK SET_MAKE am__leading_dot MAINTAINER_MODE_TRUE MAINTAINER_MODE_FALSE MAINT EMACS lispdir CC CFLAGS LDFLAGS CPPFLAGS ac_ct_CC EXEEXT OBJEXT DEPDIR am__include am__quote AMDEP_TRUE AMDEP_FALSE AMDEPBACKSLASH CCDEPMODE am__fastdepCC_TRUE am__fastdepCC_FALSE CPP EGREP RANLIB ac_ct_RANLIB LN_S X_CFLAGS X_PRE_LIBS X_LIBS X_EXTRA_LIBS LIBOBJS ALSA_CFLAGS ALSA_LIBS ARTS_CONFIG ARTS_CFLAGS ARTS_LIBS ESD_CONFIG ESD_CFLAGS ESD_LIBS VORBIS_CFLAGS VORBIS_LIBS VORBISFILE_LIBS VORBISENC_LIBS OGG_CFLAGS OGG_LIBS NEEDDLOPEN_TRUE NEEDDLOPEN_FALSE ENABLE_NCURSES_TRUE ENABLE_NCURSES_FALSE n_so_libs ENABLE_SLANG_TRUE ENABLE_SLANG_FALSE s_so_libs ENABLE_MOTIF_TRUE ENABLE_MOTIF_FALSE m_so_libs ENABLE_TCLTK_TRUE ENABLE_TCLTK_FALSE k_so_libs ENABLE_DYNAMIC_TCLTK_TRUE ENABLE_DYNAMIC_TCLTK_FALSE ENABLE_EMACS_TRUE ENABLE_EMACS_FALSE e_so_libs ENABLE_VT100_TRUE ENABLE_VT100_FALSE T_so_libs ENABLE_XAW_TRUE ENABLE_XAW_FALSE a_so_libs ENABLE_DYNAMIC_XAW_TRUE ENABLE_DYNAMIC_XAW_FALSE ENABLE_XSKIN_TRUE ENABLE_XSKIN_FALSE i_so_libs ENABLE_GTK_TRUE ENABLE_GTK_FALSE GTK_CONFIG GTK_CFLAGS GTK_LIBS g_so_libs ENABLE_SERVER_TRUE ENABLE_SERVER_FALSE r_so_libs ENABLE_ALSASEQ_TRUE ENABLE_ALSASEQ_FALSE A_so_libs ENABLE_WINSYN_TRUE ENABLE_WINSYN_FALSE W_so_libs ENABLE_W32G_SYN_TRUE ENABLE_W32G_SYN_FALSE ENABLE_W32GUI_TRUE ENABLE_W32GUI_FALSE w_so_libs ENABLE_PLUGIN_TRUE ENABLE_PLUGIN_FALSE p_so_libs ENABLE_NETWORK_TRUE ENABLE_NETWORK_FALSE ENABLE_SOUND_SPEC_TRUE ENABLE_SOUND_SPEC_FALSE ENABLE_WRD_TRUE ENABLE_WRD_FALSE CYGNUS_TRUE CYGNUS_FALSE MINGW_TRUE MINGW_FALSE W32READDIR_TRUE W32READDIR_FALSE timidity_LDFLAGS SYSEXTRAS EXTRALIBS NETSRCS ELFILES SHLD SHCFLAGS dynamic_targets so WISH tcltk_dep INTERFACE_SRCS pkgdatadir pkglibdir LTLIBOBJS'
 ac_subst_files=''
 
 # Initialize some variables set by options.
@@ -863,22 +863,23 @@ Optional Features:
   --disable-dependency-tracking Speeds up one-time builds
   --enable-dependency-tracking  Do not reject slow dependency extractors
   --enable-audio=mode_list Enable audio (Specify comma separated mode list):
-                              default: Automatically select audio device.
-                              oss:     OSS /dev/dsp
-                              sun:     SunOS /dev/audio
-                              hpux:    HPUX /dev/audio
-                              irix:    IRIX audio library
-                              mme:     OSF/1 MME
-                              sb_dsp:  BSD/OS 2.0 /dev/sb_dsp
-                              w32:     Windows MMS
-                              darwin:  Darwin CoreAudio
-                              alsa:    ALSA pcm device
-                              alib:    HPUX network audio (Alib)
-                              nas:     NAS - Network Audio System
-                              arts:    aRts
-                              esd:     EsounD - Enlightened Sound Daemon
-                              vorbis:  Ogg Vorbis
-                              gogo:    MP3 GOGO (Only Windows is supported)
+                              default:   Automatically select audio device.
+                              oss:       OSS /dev/dsp
+                              sun:       SunOS /dev/audio
+                              hpux:      HPUX /dev/audio
+                              irix:      IRIX audio library
+                              mme:       OSF/1 MME
+                              sb_dsp:    BSD/OS 2.0 /dev/sb_dsp
+                              w32:       Windows MMS
+                              darwin:    Darwin CoreAudio
+                              alsa:      ALSA pcm device
+                              alib:      HPUX network audio (Alib)
+                              nas:       NAS - Network Audio System
+                              arts:      aRts
+                              esd:       EsounD - Enlightened Sound Daemon
+                              portaudio: PortAudio
+                              vorbis:    Ogg Vorbis
+                              gogo:      MP3 GOGO (Only Windows is supported)
   --disable-alsatest      Do not try to compile and run a test Alsa program
   --disable-artstest       Do not try to compile and run a test ARTS program
   --disable-esdtest       Do not try to compile and run a test ESD program
@@ -903,6 +904,8 @@ Optional Features:
   --enable-alsaseq        Enable ALSA sequencer server interface
                                                           (default is no)
   --enable-winsyn        Enable Windows Synthesizer interface
+                                                          (default is no)
+  --enable-winsyng        Enable Windows GUI Synthesizer interface
                                                           (default is no)
   --enable-w32gui         Enable Windows GUI interface    (default is no)
   --enable-ump            UMP configuration               (default is no)
@@ -936,7 +939,7 @@ Optional Packages:
   --with-default-output=<mode>  Specify default output mode (optional):
                                 (default|alsa|alib|arts|nas|
                                 esd|wav|au|aiff|list|vorbis|
-                                gogo)
+                                gogo|portaudio)
   --with-alsa-prefix=PFX  Prefix where Alsa library is installed(optional)
   --with-alsa-inc-prefix=PFX  Prefix where include libraries are (optional)
   --with-arts-prefix=PFX   Prefix where ARTS is installed (optional)
@@ -10406,7 +10409,7 @@ fi;
 # audio section
 #
 
-audio_targets='default oss alsa sun hpux irix mme sb_dsp w32 alib nas arts esd vorbis gogo'
+audio_targets='default oss alsa sun hpux irix mme sb_dsp w32 alib nas arts esd vorbis gogo portaudio'
 
 
 # Check whether --with-nas-library or --without-nas-library was given.
@@ -10718,6 +10721,10 @@ echo $ECHO_N "checking enable_audio=w32... $ECHO_C" >&6
 if test "x$au_enable_w32" = xyes; then
   case "$target" in
     *-*-cygwin*)
+     echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+     ;;
+    *-*-mingw32)
      echo "$as_me:$LINENO: result: yes" >&5
 echo "${ECHO_T}yes" >&6
      ;;
@@ -11846,6 +11853,19 @@ else
 echo "${ECHO_T}no" >&6
 fi
 
+echo "$as_me:$LINENO: checking enable_audio=portaudio" >&5
+echo $ECHO_N "checking enable_audio=portaudio... $ECHO_C" >&6
+if test "x$au_enable_portaudio" = xyes; then
+  echo "$as_me:$LINENO: result: yes" >&5
+echo "${ECHO_T}yes" >&6
+  SYSEXTRAS="$SYSEXTRAS portaudio_a.c"
+  EXTRALIBS="$EXTRALIBS -lportaudio"
+  EXTRADEFS="$EXTRADEFS -DAU_PORTAUDIO"
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
 echo "$as_me:$LINENO: checking enable_audio=vorbis" >&5
 echo $ECHO_N "checking enable_audio=vorbis... $ECHO_C" >&6
 if test "x$au_enable_vorbis" = xyes; then
@@ -12301,6 +12321,7 @@ case ".$DEFAULT_PLAYMODE" in
   .nas)      TIMIDITY_OUTPUT_ID=n ;;
   .arts)     TIMIDITY_OUTPUT_ID=R ;;
   .esd)      TIMIDITY_OUTPUT_ID=e ;;
+  .portaudio)      TIMIDITY_OUTPUT_ID=p ;;
   .wav)      TIMIDITY_OUTPUT_ID=w ;;
   .au)       TIMIDITY_OUTPUT_ID=u ;;
   .aiff)     TIMIDITY_OUTPUT_ID=a ;;
@@ -12316,7 +12337,7 @@ echo "${ECHO_T}$DEFAULT_PLAYMODE/$TIMIDITY_OUTPUT_ID" >&6
 # Interface Section
 #
 
-interface_targets='dynamic ncurses slang motif tcltk emacs vt100 xaw xskin gtk alsaseq winsyn'
+interface_targets='dynamic ncurses slang motif tcltk emacs vt100 xaw xskin gtk alsaseq winsyn winsyng'
 
 # Check whether --enable-interface or --disable-interface was given.
 if test "${enable_interface+set}" = set; then
@@ -15060,6 +15081,54 @@ esac
 
 
 
+if false; then
+  ENABLE_W32G_SYN_TRUE=
+  ENABLE_W32G_SYN_FALSE='#'
+else
+  ENABLE_W32G_SYN_TRUE='#'
+  ENABLE_W32G_SYN_FALSE=
+fi
+
+# Check whether --enable-winsyng or --disable-winsyng was given.
+if test "${enable_winsyng+set}" = set; then
+  enableval="$enable_winsyng"
+  case "x$enable_winsyng" in xyes|xdynamic)  ;; esac
+fi;
+case "x$enable_winsyng" in
+xyes)
+  cat >> confdefs.h <<EOF
+#define IA_W32G_SYN 1
+EOF
+
+
+
+if true; then
+  ENABLE_W32G_SYN_TRUE=
+  ENABLE_W32G_SYN_FALSE='#'
+else
+  ENABLE_W32G_SYN_TRUE='#'
+  ENABLE_W32G_SYN_FALSE=
+fi
+
+   lib_w32gui_opt='-lgdi32 -lcomctl32 -lcomdlg32 -lole32'
+    lib_user32_opt='-luser32'
+    LDFLAGS="-mwindows $LDFLAGS"
+    INTERFACE_SRCS="$INTERFACE_SRCS w32g_ini.c w32g_pref.c w32g_syn.c w32g_utl.c w32g_ogg_dll.c w32g_vorbis_dll.c w32g_vorbisenc_dll.c winsyn_c.c"
+
+  ;;
+xdynamic)
+  dynamic_targets="$dynamic_targets interface_W.\$(so)"
+
+  ;;
+*)
+
+  ;;
+esac
+
+
+
+
+
 
 if false; then
   ENABLE_W32GUI_TRUE=
@@ -15093,7 +15162,7 @@ fi
    lib_w32gui_opt='-lgdi32 -lcomctl32 -lcomdlg32 -lole32'
     lib_user32_opt='-luser32'
     LDFLAGS="-mwindows $LDFLAGS"
-    INTERFACE_SRCS="$INTERFACE_SRCS w32g_c.c w32g_ini.c w32g_i.c w32g_playlist.c w32g_utl.c w32g_pref.c w32g_subwin.c w32g_ut2.c"
+    INTERFACE_SRCS="$INTERFACE_SRCS w32g_c.c w32g_ini.c w32g_i.c w32g_playlist.c w32g_utl.c w32g_pref.c w32g_subwin.c w32g_subwin2.c w32g_subwin3.c w32g_ut2.c w32g_dib.c  wrdt_w32g.c w32g_mag.c"
 
   ;;
 xdynamic)
@@ -16286,6 +16355,20 @@ echo "$as_me: error: conditional \"ENABLE_WINSYN\" was never defined.
 Usually this means the macro was only invoked conditionally." >&2;}
    { (exit 1); exit 1; }; }
 fi
+if test -z "${ENABLE_W32G_SYN_TRUE}" && test -z "${ENABLE_W32G_SYN_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"ENABLE_W32G_SYN\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"ENABLE_W32G_SYN\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
+if test -z "${ENABLE_W32G_SYN_TRUE}" && test -z "${ENABLE_W32G_SYN_FALSE}"; then
+  { { echo "$as_me:$LINENO: error: conditional \"ENABLE_W32G_SYN\" was never defined.
+Usually this means the macro was only invoked conditionally." >&5
+echo "$as_me: error: conditional \"ENABLE_W32G_SYN\" was never defined.
+Usually this means the macro was only invoked conditionally." >&2;}
+   { (exit 1); exit 1; }; }
+fi
 if test -z "${ENABLE_W32GUI_TRUE}" && test -z "${ENABLE_W32GUI_FALSE}"; then
   { { echo "$as_me:$LINENO: error: conditional \"ENABLE_W32GUI\" was never defined.
 Usually this means the macro was only invoked conditionally." >&5
@@ -17024,6 +17107,8 @@ s,@A_so_libs@,$A_so_libs,;t t
 s,@ENABLE_WINSYN_TRUE@,$ENABLE_WINSYN_TRUE,;t t
 s,@ENABLE_WINSYN_FALSE@,$ENABLE_WINSYN_FALSE,;t t
 s,@W_so_libs@,$W_so_libs,;t t
+s,@ENABLE_W32G_SYN_TRUE@,$ENABLE_W32G_SYN_TRUE,;t t
+s,@ENABLE_W32G_SYN_FALSE@,$ENABLE_W32G_SYN_FALSE,;t t
 s,@ENABLE_W32GUI_TRUE@,$ENABLE_W32GUI_TRUE,;t t
 s,@ENABLE_W32GUI_FALSE@,$ENABLE_W32GUI_FALSE,;t t
 s,@w_so_libs@,$w_so_libs,;t t
