fix for configure bugs

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -883,6 +883,7 @@ Optional Features:
                               ao:        Libao
                               vorbis:    Ogg Vorbis
                               flac:      FLAC / OggFLAC
+                              speex:     Ogg Speex
                               gogo:      MP3 GOGO (Only Windows is supported)
   --disable-alsatest      Do not try to compile and run a test Alsa program
   --disable-artstest       Do not try to compile and run a test ARTS program
@@ -946,7 +947,7 @@ Optional Packages:
   --with-nas-includes=DIR NAS include files are in dir
   --with-default-output=<mode>  Specify default output mode (optional):
                                 (default|alsa|alib|arts|nas|
-                                esd|wav|au|aiff|list|vorbis|flac|
+                                esd|wav|au|aiff|list|vorbis|flac|speex|
                                 gogo|portaudio|jack|ao)
   --with-alsa-prefix=PFX  Prefix where Alsa library is installed(optional)
   --with-alsa-inc-prefix=PFX  Prefix where include libraries are (optional)
@@ -12339,7 +12340,7 @@ fi
     esac
 done
 
-    LIBS="$KEEPLIBS $ALSA_LIBS"
+    LIBS="$LIBS $ALSA_LIBS"
 
 for ac_func in snd_seq_port_info_set_timestamping
 do
@@ -13643,7 +13644,7 @@ echo "${ECHO_T}yes" >&6
     esac
 done
 
-    LIBS="$KEEPLIBS $AO_LIBS"
+    LIBS="$LIBS $AO_LIBS"
   else
     { echo "$as_me:$LINENO: WARNING: Couldn't configure libao." >&5
 echo "$as_me: WARNING: Couldn't configure libao." >&2;}
@@ -14208,7 +14209,7 @@ echo "${ECHO_T}yes" >&6
     esac
 done
 
-    LIBS="$KEEPLIBS $LIBFLAC_LIBS"
+    LIBS="$LIBS $LIBFLAC_LIBS"
 
   else
      echo "$as_me:$LINENO: result: no" >&5
@@ -14414,7 +14415,7 @@ echo "${ECHO_T}yes" >&6
     esac
 done
 
-    LIBS="$KEEPLIBS $LIBOGGFLAC_LIBS"
+    LIBS="$LIBS $LIBOGGFLAC_LIBS"
 
   else
      echo "$as_me:$LINENO: result: no" >&5
@@ -14501,6 +14502,77 @@ else
 echo "${ECHO_T}no" >&6
 fi
 
+echo "$as_me:$LINENO: checking enable_audio=speex" >&5
+echo $ECHO_N "checking enable_audio=speex... $ECHO_C" >&6
+if test "x$au_enable_speex" = xyes; then
+  if test "${have_speex+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+  #include <speex.h>
+  #include <ogg/ogg.h>
+
+int
+main ()
+{
+
+    SpeexBits *dummy;
+
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (eval echo "$as_me:$LINENO: \"$ac_link\"") >&5
+  (eval $ac_link) 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } &&
+	 { ac_try='test -z "$ac_c_werror_flag"
+			 || test ! -s conftest.err'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; } &&
+	 { ac_try='test -s conftest$ac_exeext'
+  { (eval echo "$as_me:$LINENO: \"$ac_try\"") >&5
+  (eval $ac_try) 2>&5
+  ac_status=$?
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); }; }; then
+  have_speex=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+have_speex=no
+fi
+rm -f conftest.err conftest.$ac_objext \
+      conftest$ac_exeext conftest.$ac_ext
+fi
+
+  echo "$as_me:$LINENO: result: $have_speex" >&5
+echo "${ECHO_T}$have_speex" >&6
+  if test "x$have_speex" = xyes; then
+    SYSEXTRAS="$SYSEXTRAS speex_a.c"
+    EXTRALIBS="$EXTRALIBS -lspeex -logg"
+    EXTRADEFS="$EXTRADEFS -DAU_SPEEX"
+  fi
+else
+  echo "$as_me:$LINENO: result: no" >&5
+echo "${ECHO_T}no" >&6
+fi
+
 echo "$as_me:$LINENO: checking enable_audio=gogo" >&5
 echo $ECHO_N "checking enable_audio=gogo... $ECHO_C" >&6
 if test "x$au_enable_gogo" = xyes; then
@@ -14556,6 +14628,7 @@ case ".$DEFAULT_PLAYMODE" in
   .list)     TIMIDITY_OUTPUT_ID=l ;;
   .vorbis)   TIMIDITY_OUTPUT_ID=v ;;
   .flac)     TIMIDITY_OUTPUT_ID=F ;;
+  .speex)    TIMIDITY_OUTPUT_ID=S ;;
   .gogo)     TIMIDITY_OUTPUT_ID=g ;;
   .jack)     TIMIDITY_OUTPUT_ID=j ;;
   *)         TIMIDITY_OUTPUT_ID= ;;
